# .github/workflows/make.yml

name: Update Submodules

on:
  release: # Trigger on release
    types: []

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Make Command
        run: make update
